### ISSUE TITLE
CredentialsError: Missing credentials in config

### ISSUE THREAD

**Issue by dsdenes** [mentum/lambdaws#34]
// accessKey and secretKey parameters must be provided in the root of the settings object

lambdaws.config({
	accessKey: '',
	secretKey: ''
});

// instead of

lambdaws.config({
	credentials: {
		accessKey: '',
		secretKey: ''
	},
});

**Comment by slvnperron** [comment]
Please see lambdaws.js line 64-66

**Comment by slvnperron** [comment]
@dsdenes I am closing this issue as we can't reproduce it without your input. Please reopen with appropriate reproduction steps if you are experiencing an issue.
