### ISSUE TITLE
Long execution times

### ISSUE THREAD

**Issue by jbeard4** [mentum/lambdaws#55]
I'm seeing consistent execution times of about 3s for the functions included in example.js

![](https://www.dropbox.com/s/kgyu80g6veaar80/Screenshot%202015-02-03%2000.16.46.png?dl=1)

It seems unlikely that this is Lambda execution time, so I'm wondering, where is this time being spent?

**Comment by EFF** [comment]
Hi there !




The time spent comes directly from aws. They added an annoying extra 2 s. between the time you invoke the function and the time it actually get called on aws.




We filled a ticket and got a reply from the aws team telling us that it'll go away after the preview periode.




Thanks for telling us though!!



—
François-Xavier P. Darveau
software consultant | mentum

Super powered by Mailbox for iPhone

**Comment by jbeard4** [comment]
Thanks for the reply.

**Comment by EFF** [comment]
@jbeard4 No problem ! If you have any other questions or requests, feel free !
